name: "Package and Test kpindex"

on:
  workflow_call:
    inputs: 
      python_version:
        type: string
        description: "Python version to use for packaging and tests"
        required: true
      upload_github:
        type: string
        description: "Upload package to github"
        default: "false"
      upload_pypi:
        type: string
        description: "Upload package to PyPI"
        default: "false"
      run_tests:
        type: string
        description: "Run tests"
        default: "true"
jobs:
  package_and_test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
           
      - name: Build Docker Image
        run: |
          pyver="${{ inputs.python_version }}"
          pyref="py${pyver//./}"
          docker_image="kpindex:${pyref}"
          echo "Docker image: ${docker_image}"
          echo "docker_image=${docker_image}" >> $GITHUB_ENV
          docker build --target $pyref -t $docker_image .

      - name: Run Docker Image
        run: |
          echo "docker_image is '${{ env.docker_image }}'"
          docker_container=kptest
          echo "docker_container=$docker_container" >> $GITHUB_ENV
          docker run --name $docker_container --rm -d ${{ env.docker_image }}

      - name: Build Package
        run: |
          docker exec -u kp ${{ env.docker_container }} bash -c "cd /kpindex && source /app/venv/bin/activate && python setup.py bdist_wheel"
          pkg=$(docker exec -u kp ${{ env.docker_container }} bash -c "cd /kpindex/dist && ls")
          echo "Built package: $pkg"
          echo "pkg=$pkg" >> $GITHUB_ENV

      - name: Install Package
        run: |
          docker exec -u kp ${{ env.docker_container }} bash -c "cd /kpindex/dist && /app/venv/bin/pip install $pkg"

      - name: Copy Package
        run: |
          docker cp $docker_container:/kpindex/dist/$pkg .

      - name: Test Update
        if: ${{ inputs.run_tests == 'true' }}
        run: |
          echo "Run update test"

      - name: Test Read
        if: ${{ inputs.run_tests == 'true' }}
        run: |
          echo "Run read test"

      - name: Test Get
        if: ${{ inputs.run_tests == 'true' }}
        run: |
          echo "Run get test"
          
      - name: Upload to GitHub
        if: ${{ inputs.upload_github == 'true' }}
        run: |
          echo "Upload to GitHub"

      - name: Upload to PyPI
        if: ${{ inputs.upload_pypi == 'true' }}
        run: |
          echo "Upload to PyPI"

      - name: Clean Up
        if: always()
        run: |
          docker stop ${{ env.docker_container }}